[degiro_server]
country = "NL"
lang = "nl"
ga_ext = "/totp"
login_url = "https://trader.degiro.nl/login/secure/login"
client_url = "https://trader.degiro.nl/pa/secure/client"
portfolio_url = "https://trader.degiro.nl/portfolio-reports/secure/v3/positionReport/csv"
account_url = "https://trader.degiro.nl/portfolio-reports/secure/v3/cashAccountReport/csv"
user_agent = "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:107.0) Gecko/20100101 Firefox/107.0"
